"""Initial migration

Revision ID: 885d8cd79ec1
Revises: 
Create Date: 2025-02-10 18:53:28.217722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885d8cd79ec1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('found_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('date_found', sa.Date(), nullable=False),
    sa.Column('contact_info', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lost_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('date_lost', sa.Date(), nullable=False),
    sa.Column('contact_info', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lost_item')
    op.drop_table('found_item')
    # ### end Alembic commands ###
