"""Add image field to items

Revision ID: d1f58c0a4830
Revises: 7ce697b9cfe2
Create Date: 2025-02-11 20:38:41.823461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1f58c0a4830'
down_revision = '7ce697b9cfe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('found_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))

    with op.batch_alter_table('lost_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lost_item', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    with op.batch_alter_table('found_item', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
